# -*- mode: python ; coding: utf-8 -*-

import os
project_root = os.path.dirname(os.path.abspath(SPEC))

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['D:\\dataset\\asset_system2'],
    binaries=[],
    datas=[
        ('assets_pro.db', '.'),
        ('images', 'images'),
        ('assets', 'assets'),
        ('app_icon.ico', '.'),
        ('map_api_keys.json', '.'),
    ],
    hiddenimports=[
        'PIL',
        'PIL._tkinter_finder',
        'sqlite3',
        'openpyxl',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'hashlib',
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtWidgets',
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtWebEngineCore',
        'PyQt5.QtWebChannel',
        'PyQt5.QtGui',
        'requests',
        'json',
        'tempfile',
        'config.database',
        'config.map_config',
        'services.auth',
        'services.geocoding',
        'gui.map.map_view',
        'gui.map.map_launcher',
        'gui.map.map_standalone',
        'gui.map.map_diagnose',
        'gui.login',
        'gui.main_window',
        'gui.home',
        'gui.assets',
        'gui.departments',
        'gui.users',
        'utils.utils',
        'math',
        'threading',
        'datetime',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AssetManagementSystem',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app_icon.ico'],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AssetManagementSystem',
)